import { PageHeader } from "@/app/components/pageHeader";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Signature Generator",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PageHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
